### ISSUE TITLE
Allow ignoring tracing of configured payloads

### ISSUE THREAD

**Issue by ojongerius** [epsagon/serverless-plugin-epsagon#106]
We'd love to be able to disable tracing for Lamba invocations that are triggered by warmup events. We use the "serverless-plugin-warmup" plugin, and I have raised https://github.com/epsagon/epsagon-python/pull/370 with a crude implementation of ignoring the default payloads sent by that plugin. 

A nicer implementation would be to have this plugin take a list if k/vs to ignore. That would allow the warmup plugin to change independently, and other user cases. A fancier implementation would take a jmespath and value, but that might be over the top.

If this would be support the python and JS libraries could test if ignoredPayloads are configured, and if so, skip instrumenting matching payload key / values. This is an example of how a user would configure this in their serverless.yml

```
custom:
  epsagon:
    token: epsagon-token
    appName: app-name-stage
    ignoredPayloads:
      - source: serverless-plugin-warmup
```
