### ISSUE TITLE
Unable to import module 'epsagon_handlers/...

### ISSUE THREAD

**Issue by tainguyenbui** [epsagon/serverless-plugin-epsagon#31]
Runtime: Python 2.7

Description: When using Epsagon Serverless Plugin it would not work. If Epsagon is disabled works as expected.

error message: "Unable to import module 'epsagon_handlers/..."

![screenshot 2019-01-04 at 11 47 52](https://user-images.githubusercontent.com/4402762/50686770-9a908c00-1016-11e9-8986-186047c50c31.png)

Module available in functions code

**Comment by ranrib** [comment]
Thanks for letting us know @tainguyenbui,

Can you please share a snippet of your `serverless.yml` file? (the includes epsagon, provider, and an example function)?

Thanks!

**Comment by tainguyenbui** [comment]
Hi @ranrib!

yes definitely. This is the `serverless.yml`

```
service: ${self:custom.config.service}
package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - polly:SynthesizeSpeech
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - sns:Publish
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetBucketLocation
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: [
          "*"
        ]

plugins:
  - serverless-plugin-epsagon

custom:
  config: ${file(config.yml)}
  postsTable: ${self:service}-${self:provider.stage}
  mediaBucketName: ${self:service}-media-${self:provider.stage}
  snsTopicName: ${self:service}-topic-${self:provider.stage}
  snsTopicArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopicName}" ] ]  }
  epsagon:
    token: ${self:custom.config.epsagonToken}
    appName: ${self:service}
    disable: false

functions:
  getPosts:
    handler: functions/getPosts.lambda_handler
    package:
      include:
        - functions/getPosts.py
    description: Get posts from Posts table
    memorySize: 512
    environment:
      POSTS_TABLE: ${self:custom.postsTable}
      EPSAGON_TOKEN: ${self:custom.epsagon.token}
      EPSAGON_APPNAME: ${self:custom.epsagon.appName}
    events:
      - http:
          method: get
          path: /
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{"postId" : "$input.params("postId")"}'
            passThrough: NEVER
    epsagon:
      wrapper: lambda_wrapper

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.postsTable}
    PostsAudioBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.mediaBucketName}
```

and this is the function code:

```
import boto3
import os
from boto3.dynamodb.conditions import Key, Attr

def lambda_handler(event, context):
    
    postId = event["postId"]
    
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table(os.environ['POSTS_TABLE'])
    
    if postId=="*":
        items = table.scan()
    else:
        items = table.query(
            KeyConditionExpression=Key('id').eq(postId)
        )
    
    return items["Items"]
```

thanks for looking into it :D
