### ISSUE TITLE
Config value to disable Epsagon function at service level is not used

### ISSUE THREAD

**Issue by ky-cheng** [epsagon/serverless-plugin-epsagon#45]
Setting config value for disable = false at the service level is not respected.
In `src/index.js` line 99 `if (this.config().disable)`

This I guess is checking just for the existing of the config attribute and not checking the actual value to equal true so it cannot be used to control whether epsagon is disable or not. We are relying on this config value so we can disable epsagon for specific environment

Perhaps it can be changed to:
`if (this.config().disable && this.config().disable === 'true')`?

Cheers, Ky

**Comment by ranrib** [comment]
Hi @ky-cheng - I tried now with the following configuration:
```
custom:
  epsagon:
    token: your-token-here
    appName: optional-application-name
    disable: false
```

And I got the functions wrapped succesfully.
Can you please give me an input that fails? Please note that the input should be boolean type and not text.

Thanks
