### ISSUE TITLE
Error: Identifier 'handler' has already been declared

### ISSUE THREAD

**Issue by chadjvw** [epsagon/serverless-plugin-epsagon#59]
TypeScript code is failing to compile after merging of #54 if the original method name is `handler`.

Generated code -> `KeepWarm-epsagon.ts`
```typescript
import epsagon from 'epsagon';
import * as handler from '../src/keep-warm';

epsagon.init({
    token: 'token',
    appName: 'app-name',
    traceCollectorURL: undefined,
    metadataOnly: Boolean(0)
});

export const handler = epsagon.lambdaWrapper(handler.handler);
```

Webpack error
```
ERROR in ./epsagon_handlers/KeepWarm-epsagon.ts 9:13
Module parse failed: Identifier 'handler' has already been declared (9:13)
File was processed with these loaders:
 * ../../node_modules/cache-loader/dist/cjs.js
 * ../../node_modules/thread-loader/dist/cjs.js
 * ../../node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     metadataOnly: Boolean(0)
| });
> export const handler = epsagon.lambdaWrapper(handler.handler);
|
```
serverless.yml
```yaml
  epsagon:
    token: ${env:EPSAGON_TOKEN, file(../../secrets.yml):epsagon.token}
    appName: app-name

functions:
  KeepWarm:
    handler: src/keep-warm.handler
    description: Keep specific lambda functions warm by invoking them every 10 minutes during work hours so we dont have to cold start them
    role: KeepWarmRole
```
Possibly related: #39
