### ISSUE TITLE
Breaks serverless-offline plugin

### ISSUE THREAD

**Issue by thesmith** [epsagon/serverless-plugin-epsagon#66]
If you're running the epsagon plugin while running your app locally through https://github.com/dherault/serverless-offline the local http request processing fails.

You can reproduce with a totally vanilla project with an http endpoint.

**Comment by tvaintrob** [comment]
Hi, can you share your `serverless.yml`, i can't seem to reproduce the issue

**Comment by thesmith** [comment]
I've had to sanitize but hopefully this gives you everything you need.

```yaml
service: ...

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: eu-west-1
  role: ...
  vpc:
    securityGroupIds:
      - ...
    subnetIds:
      - ...
  memorySize: 256
  timeout: 50
  deadLetter:
    targetArn: ...

functions:
  app:
    handler: lambda_handler.app
    events:
      - http:
          path: ...
          method: get
          authorizer: auth
          cors: true
  auth:
    handler: lambda_handler.auth
    cors: true

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

plugins:
  - serverless-python-requirements
  - serverless-plugin-lambda-dead-letter
  - serverless-plugin-epsagon
  - serverless-offline
custom:
  epsagon:
    token: ...
    appName: ...
```
