### ISSUE TITLE
Function level options throw Configuration warning during sls deploy

### ISSUE THREAD

**Issue by uccmen** [epsagon/serverless-plugin-epsagon#95]
## Library version, runtime version, dependencies, etc.
- epsagon: v1.106.2
- serverless-plugin-epsagon: v1.10.2
- serverless: v2.17.0
- node: v12.21.0
- npm: v6.14.11

## Snippet of the usage.
```yaml
editContentPanelGeneralHandler:
    handler: handler.editContentPanelGeneral
    epsagon:
      disable: true
...
install:
    handler: handler.install
    epsagon:
      disable: true
```
## Warning thrown when running sls deploy
<img width="1096" alt="Screenshot 2021-03-26 at 9 06 03 PM" src="https://user-images.githubusercontent.com/1238697/112636817-898ef800-8e78-11eb-8861-605d8704e36c.png">

## However, it does seem that the plugin registers the option passed in
<img width="1092" alt="Screenshot 2021-03-26 at 9 06 21 PM" src="https://user-images.githubusercontent.com/1238697/112637105-c35ffe80-8e78-11eb-90a9-d73b3c26f069.png">
