### ISSUE TITLE
Enabling epsagon tracing at service level causes sls deploy to take a really long time

### ISSUE THREAD

**Issue by uccmen** [epsagon/serverless-plugin-epsagon#96]
## Library version, runtime version, dependencies, etc.
- epsagon: v1.106.2
- serverless-plugin-epsagon: v1.10.2
- serverless: v2.17.0
- node: v12.21.0
- npm: v6.14.11

## Snippet of the usage.
```yaml
...
plugins:
  - serverless-plugin-epsagon
  - serverless-webpack
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline

...
custom:
  epsagon:
    token: ${opt:epsagonToken}
    appName: ${self:service}-${self:provider.stage}
    disable: false
    metadataOnly: false
```

## Details
I found out when `disable` option is set to `false`, allowing our functions to be wrapped with Epsagon wrapper, it causes `sls deploy` to take a really long time to complete about 8+ minutes as opposed when `disable` is set to `true`, it only takes 1+ minute to deploy all 18 of our functions

## When epsagon is enabled (sls deploy took ~8 minutes)
<img width="933" alt="Screenshot 2021-03-26 at 9 37 22 PM" src="https://user-images.githubusercontent.com/1238697/112639952-d32d1200-8e7b-11eb-9a34-9fc27e218790.png">

## When epsagon is disabled (sls deploy took ~2 minute)
<img width="895" alt="Screenshot 2021-03-26 at 9 42 14 PM" src="https://user-images.githubusercontent.com/1238697/112640414-4767b580-8e7c-11eb-9e9b-6d201e6e3acf.png">

This is expensive to us because we use Github Action to run our deployments and our app which has epsagon enabled eats up most of our provisioned minutes.

Even more worried if the list of functions grow, sls deploy could take even longer?
